name: Deploy Static Website (Full Repo, Filtered)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Clean up unwanted folders before upload
      - name: Remove .git and .github
        run: |
          rm -rf .git .github

      # Copy everything else to the VPS
      - name: Copy project files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # port: ${{ secrets.VPS_PORT }} # Uncomment if using a custom SSH port
          source: "./*"
          target: ${{ secrets.APP_PATH }}
          rm: true   # Makes the server folder match the repo exactly (optional, recommended for static sites)
